In [23]:
import torch
import numpy as np

In [8]:
# You can decide the shape of the tensor (similar to arrays)
x = torch.empty(2,3)

# Initializing a tensor with random values | There are similar initialization methods to numpy.
y = torch.rand(2, 2)
print(y.size())

# You can also initialize a tensor by providing a list/tuple
mylist = [1,2,3,4,5]
mytensor = torch.tensor(mylist)
mytensor

torch.Size([2, 2])


tensor([1, 2, 3, 4, 5])

In [13]:
# Basic tensor operations
xTensor = torch.rand(2,2)
yTensor = torch.rand(2,2)
zTensor = xTensor + yTensor
print(zTensor)

# We can also do inplace additions
yTensor.add_(xTensor)
print(yTensor)

# Subtraction
difference = xTensor - yTensor
difference = torch.sub(xTensor, yTensor)
print(difference)

# Multiplication + inplace multiplication
product = xTensor * yTensor
product = torch.mul(xTensor, yTensor)
yTensor.mul_(xTensor)
print(difference)

tensor([[0.9424, 0.9904],
        [0.3153, 0.9094]])
tensor([[0.9424, 0.9904],
        [0.3153, 0.9094]])
tensor([[-0.2738, -0.6109],
        [-0.0213, -0.1670]])


In [19]:
# Manipulating data selection within the tensor
myTensor = torch.rand(4,4)
myTensor[:,1]

tensor([0.4226, 0.5123, 0.8428, 0.1058])

In [22]:
# Reshaping a tensor, number of elements must match.
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

# If you don't know one of the dimensions you can your tensor to take we can do this.
y = x.view(2, -1)
print(y.size())

tensor([[0.8037, 0.9524, 0.5910, 0.7497],
        [0.6863, 0.7238, 0.8308, 0.2597],
        [0.2538, 0.3676, 0.8561, 0.5982],
        [0.3238, 0.4280, 0.5869, 0.0465]])
tensor([0.8037, 0.9524, 0.5910, 0.7497, 0.6863, 0.7238, 0.8308, 0.2597, 0.2538,
        0.3676, 0.8561, 0.5982, 0.3238, 0.4280, 0.5869, 0.0465])
torch.Size([2, 8])


In [37]:
# Converting numpy to pytorch
a = torch.ones(5)
print(type(a))
b = a.numpy()
print(type(b))

c = np.zeros([5,5])
print(type(c), f'\n{c}')
d = torch.from_numpy(c)
print(type(d), f'\n{d}')

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'> 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'torch.Tensor'> 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [36]:
# Checking if CUDA is available
if torch.cuda.is_available():
    print('YES')