In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

## Tensor Initialization
> Similar to arrays in NumPy (very similar)

In [3]:
# Print an empty tensor
x = torch.empty(1)
x

tensor([1.0102e-38])

In [5]:
# Create an empty tensor with 3 elements
x = torch.empty(3)
x

tensor([1.4013e-45, 0.0000e+00, 0.0000e+00])

In [6]:
# Multidimension empty tensor
y = torch.empty(4,5)
y

tensor([[9.0919e-39, 9.2755e-39, 2.9389e-39, 1.0286e-38, 1.0469e-38],
        [1.0653e-38, 1.0194e-38, 2.9389e-39, 1.0194e-38, 9.9184e-39],
        [2.9389e-39, 1.0194e-38, 2.9389e-39, 9.2755e-39, 9.0918e-39],
        [1.0010e-38, 9.9184e-39, 1.0653e-38, 9.1837e-39, 9.6428e-39]])

In [8]:
# Create a multidimensional tensor of random values
myTensor = torch.rand(3,3)
myTensor

tensor([[0.9122, 0.3889, 0.3642],
        [0.8938, 0.7431, 0.9723],
        [0.9181, 0.8056, 0.9440]])

In [9]:
# Create a tensor of ones with a specific data type
x = torch.ones(3,3, dtype=torch.float16)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [10]:
# Create a tensor from a python list
mylist = [range(10)]
x = torch.tensor(mylist)
x

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
x.dtype

torch.int64

## Vector Operations

In [15]:
# Adding tensors
x = torch.rand(3,3)
y = torch.rand(3,3)
print(x)
print(y)
x + y

tensor([[0.7699, 0.8426, 0.8165],
        [0.8363, 0.5198, 0.1512],
        [0.0243, 0.4745, 0.7425]])
tensor([[0.7932, 0.5733, 0.3395],
        [0.7518, 0.2858, 0.6651],
        [0.8218, 0.8413, 0.2651]])


tensor([[1.5632, 1.4159, 1.1560],
        [1.5881, 0.8056, 0.8162],
        [0.8461, 1.3157, 1.0075]])

In [17]:
# In place addition
x = torch.ones(3,3)
x.add_(10)
x

tensor([[11., 11., 11.],
        [11., 11., 11.],
        [11., 11., 11.]])

In [18]:
# In place subtraction
x.sub_(10)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
# We can do tensor splicing, if there is only 1 item in the selection you can use the '.item' method to return
# the actual value
x = torch.rand(3,3)
x[1,1].item()

0.2212369441986084

## Tensor Reshaping

In [25]:
x = torch.rand(4,5)
x

tensor([[0.4969, 0.0623, 0.4663, 0.3808, 0.6823],
        [0.2842, 0.8329, 0.1135, 0.3212, 0.7148],
        [0.3626, 0.3001, 0.1425, 0.2618, 0.3999],
        [0.2478, 0.6387, 0.8321, 0.4653, 0.6576]])

In [31]:
x = x.reshape(5,4)
x

tensor([[0.4969, 0.0623, 0.4663, 0.3808],
        [0.6823, 0.2842, 0.8329, 0.1135],
        [0.3212, 0.7148, 0.3626, 0.3001],
        [0.1425, 0.2618, 0.3999, 0.2478],
        [0.6387, 0.8321, 0.4653, 0.6576]])