In [1]:
import sys
import numpy as np

# Basics

In [26]:
myarr = np.array([1,2,3], dtype='float64')
print(myarr)

random = np.random.randint(101, size=[5,5])
random

[1. 2. 3.]


array([[27, 79, 79, 63, 75],
       [73, 27, 20, 69, 76],
       [64, 29, 89, 90, 65],
       [44, 45, 23, 29, 96],
       [ 0, 97, 78, 49, 52]])

In [18]:
random[2:4,1:3]

array([[42, 90],
       [53, 30]])

In [23]:
# You can select multiple individual elements from the matrix in this way.
random[[0, 2, -1]]

array([[80, 35, 96, 54, 51],
       [85, 42, 90, 77, 47],
       [82,  9, 34, 24, 59]])

## Array Types

In [27]:
myarr.dtype

dtype('float64')

In [25]:
random.shape

(5, 5)

In [40]:
charArr = np.array(['a', 'c', 'e'])
charArr.dtype

dtype('<U1')

## Dimensions and Shapes

In [29]:
random.shape

(5, 5)

In [30]:
myarr.shape

(3,)

In [31]:
random.size

25

In [32]:
charArr.size

3

In [41]:
charArr = np.append(charArr, 'b')
charArr.size

4

array(['a', 'c', 'e'], dtype='<U1')

## Basic Stats

In [43]:
sample_arr = np.random.randint(101, size=[10, 10])
sample_arr

array([[24, 51, 35, 44, 86, 22, 46, 46, 82,  7],
       [50, 58, 83, 30, 37, 46, 21, 85, 33, 66],
       [96, 24, 41, 28, 37, 92,  2, 45, 58,  3],
       [ 4, 86, 15,  4, 73, 93, 34,  1, 39, 92],
       [49, 87, 20, 62, 28, 26,  1, 90,  4, 81],
       [64,  2, 81, 39, 12, 89,  4, 20, 87,  3],
       [26, 50, 40, 97, 34, 41, 26, 36, 12,  8],
       [66, 61, 80,  6, 46, 76, 10, 43, 96, 92],
       [12, 78, 86,  2, 70, 31, 38, 81,  3, 86],
       [11, 85,  0, 64, 67, 22, 61, 68, 31, 99]])

In [44]:
sample_arr.sum()

4609

In [45]:
sample_arr.mean()

46.09

In [46]:
sample_arr.std()

30.58728330532151

In [47]:
# We can specify specific regions of the arr for stats
sample_arr[0].sum()

443

In [48]:
sample_arr[0].mean()

44.3

In [49]:
# We can also specify it by axis
sample_arr.sum(axis=0)

array([402, 582, 481, 376, 490, 538, 243, 515, 445, 537])

## Broadcasting and Vectorized Operations

In [57]:
newArr = np.arange(10)
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
newArr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [58]:
newArr += 10
newArr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
a = np.arange(10, 101)
b = np.arange(-100, - 9)
a + b

array([-90, -88, -86, -84, -82, -80, -78, -76, -74, -72, -70, -68, -66,
       -64, -62, -60, -58, -56, -54, -52, -50, -48, -46, -44, -42, -40,
       -38, -36, -34, -32, -30, -28, -26, -24, -22, -20, -18, -16, -14,
       -12, -10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10,  12,
        14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,  36,  38,
        40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,  62,  64,
        66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,  88,  90])