# The Basics

In [1]:
import numpy as np
import pandas as pd

In [2]:
## THE BASICS
# Creating a simple array.

myarray = np.array([1, 2, 3])
my2darray = np.array([[1, 2, 3], [4, 5, 6]])
myarray

## Get dimension of numpy arrays.
myarray.ndim 
my2darray.ndim

## Num of rows and cols within the array.
my2darray.shape

## Get item size of the elements of the array
my2darray.itemsize

## Get total size
my2darray.nbytes

24

# Accessing/Changing specific elements, rows, columns, etc.

In [9]:
myarray = np.array([[1, 2, 3, 4 ,5 ,6 ,7],[8, 9, 10, 11, 12, 13, 14]])

## Get a specific element [row, col]
print(myarray[1, 5])

## Get a specifc row
print(myarray[0, :])

## Get a specific col
print(myarray[:, 2])

## Getting fancy [startindex, endindex, stepsize]
print(myarray[0, 1:6:2])

## Changing something
myarray[1, 5] = 20

## Replacing an entire column
myarray[:, 2] = [1, 2]
myarray

13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]


array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

# Initializing Different Types of Arrays.

In [2]:
## ALL 0's Array
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
## ALL 1's Matrix
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [7]:
## Any other number
np.full((2, 4), 69)

array([[69, 69, 69, 69],
       [69, 69, 69, 69]])

In [10]:
## Any other full-like
np.full_like(myarray, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [11]:
## Random decimal numbers
np.random.rand(4, 2)

array([[0.75101065, 0.38407134],
       [0.20868383, 0.35237686],
       [0.83274723, 0.15572551],
       [0.30598109, 0.90801258]])

In [12]:
## Random integer values
np.random.randint(1, 100, size=(2, 2))

array([[63, 51],
       [55, 34]])

In [14]:
## Identity Matrix, square-shaped matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
## Repeat an element based upon different axis points
newArray = np.array([[1,2,3]])
e1 = np.repeat(newArray, 3, axis=0)
e1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [26]:
## Exercise
challenge = np.ones((5, 5))
challenge[1:4, 1:4] = 0
challenge[2, 2] = 9
challenge

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Mathematics

In [2]:
a = np.array([1, 2 ,3 ,4])
a

array([1, 2, 3, 4])

In [6]:
## Array element operations.
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [10]:
## Get the sin of every element within an array
print(np.sin(a))
print(np.cos(a))
print(np.cosh(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.54308063  3.76219569 10.067662   27.30823284]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


# Linear Algebra

In [12]:
## Multiplying matrices
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [14]:
## finding the identity matrix
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [15]:
stats = np.array([[1,2,3], [4, 5 ,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.min(stats, axis=1)

array([1, 4])

In [17]:
np.max(stats)

6

In [19]:
np.sum(stats, 1)

array([ 6, 15])

# Reorganizing Arrays

In [4]:
before = np.array([[1, 2, 3 ,4], [5, 6 ,7 , 8]])
before.shape

(2, 4)

In [6]:
## As long as it has the same amount of values the reshape will work.
after = before.reshape((8, 1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [9]:
## Vertical stacks, vertically stacking vectors and matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1, v2]))
# You can keep stacking these, there is not limit
print(np.vstack([v1, v2, v1, v1]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [1 2 3 4]]


In [10]:
## Horizontal stacks
h1 = np.zeros((2,4))
h2 = np.ones((2,2))

np.hstack([h1, h2])

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])